### ISSUE TITLE
Crash does not run on real Dreamcast Might be non aligned memory 

### ISSUE THREAD

**Issue by ianmicheal** [nareez/dreamcast-voxelspace-engine#1]
![bandicam 2023-01-09 04-55-44-947](https://user-images.githubusercontent.com/59771322/211283791-0802e190-c9ca-4c4e-9844-c64a6d62cda3.jpg)
Debug
OUTPUT:> Unhandled exception: PC 8c0109b2, code 1, evt 00e0
OUTPUT:>  R0-R7: 00000100 8c23c588 00000008 8c1cf6d9 00000006 00000006 8c238588 00000100
OUTPUT:>  R8-R15: 8c1cf3b8 8cfff948 8c1cf6c8 8c1cf6cd 8cfff8d8 8cfff958 8cfffc98 8cfff8c0
OUTPUT:>  SR 40000100 PR 8c010954
OUTPUT:> Stack Trace: frame pointers not enabled!
OUTPUT:> kernel panic: unhandled IRQ/Exception
OUTPUT:> arch: aborting the system
STATE:> Upload processus completed on 1/9/2023 - 04:54:58, Exit Code : 0
$ sh-elf-addr2line -e main.elf  0x08c0109b2
gif.h:113

        return -3; /** min LZW size is out of its nominal [2; 8] bounds **/
    if ((ctbl = (1L << ctsz)) != (mask & _GIF_SWAP(*(GIF_H*)(*buff + 1))))
        return -2; /** initial code is not equal to min LZW size **/

So ether some unaligned memory pointer or read or null pointer..

A real Dreamcast cant handle non aligned memory reads.. All Dreamcast emulators do which is just one of the things why there rubbish for doing development

same compiled elf works fine on dc emulator

![bandicam 2023-01-09 05-14-37-197](https://user-images.githubusercontent.com/59771322/211285273-ccd97e7c-c23a-485f-abfb-002d2bd36ff3.jpg)

**Comment by nareez** [comment]
Fixed using stb_image.h instead of gif.h lib
